version: "3.0"
services:
  mongodb:
    image: mongo:4.2
    container_name: mongodb
    command: ["--replSet", "replocal", "--bind_ip_all"]
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
  nginx-rtmp:
    image: livestream_nginx_rtmp
    container_name: nginx_rtmp
    ports:
      - 1935:1935
volumes:
  data: {}

networks:
  default:
    name: mongodb_network