version: "5.0"
services:
  mongo:
    image: mongo:4.2
    container_name: mongodb
    command: ["--replSet", "replocal", "--bind_ip_all"]
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
#  mongodb2:
#    image: mongo:4.2
#    container_name: mongodb2
#    command: ["--replSet", "replocal"]
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongo
volumes:
  data: {}

networks:
  default:
    name: mongodb_network